### ISSUE TITLE
Add the ability to toggle the popup window

### ISSUE THREAD

**Issue by excvai** [Issafalcon/lsp-overloads.nvim#18]
It would be nice to have a command that will toggle the popup . Right now when I call `LspOverloadsSignature` when it's already shown it just draws it again instead of hiding it

**Comment by Issafalcon** [comment]
Hi @excvai - For sure. I've had this thought also. While my attention is on https://github.com/Issafalcon/neotest-dotnet at the moment, I have a couple things to sort out with that first, then I plan on making some more enhancements to lsp-overloads, including this.

**Comment by Issafalcon** [comment]
@excvai - Sorry for the wait! Shame how the day job gets in the way! 😄 

The linked PR is merged and should fix this issue, and some others.

**Comment by excvai** [comment]
@Issafalcon Are you talking about LspOverloadsSignatureAutoToggle? Unfortunately, it doesn't seem like solving my problem. Yes it prevents the signature from showing by default but what I wanted is the ability to hide the signature by executing LspOverloadsSignature when it's already shown. Right now LspOverloadsSignature works as it worked before

**Comment by Issafalcon** [comment]
Hi @excvai - I mean that the built-in key mapping to close the signature window (when open) should enable you to get that "toggle" behaviour. 

It was easier to implement this mechanism than to overload the LspOverloadsSignature command. So while it isn't a true 'toggle', the README shows how to create a toggle effect by mapping the same keybind in the config that closes the signature.

If you are unable to do this for whatever reason, let me know.

**Comment by excvai** [comment]
It works perfectly! Thanks!!!
