### ISSUE TITLE
Bug when setting `floating_window_above_cur_line = true`

### ISSUE THREAD

**Issue by goingtosleep** [Issafalcon/lsp-overloads.nvim#22]
I encountered this strange gap when setting the floating position:

<img src="https://user-images.githubusercontent.com/47395035/219848638-469c946f-2bdf-48f1-a39a-244bcb0bb3a7.png" width=50%>

As I've seen, when the current line is under half-screen, the floating window will be positioned above, so no need to add `offset_y` as in [this code](https://github.com/Issafalcon/lsp-overloads.nvim/blob/main/lua/lsp-overloads/handlers.lua#L165-L167).

I tried patching [line 165](https://github.com/Issafalcon/lsp-overloads.nvim/blob/main/lua/lsp-overloads/handlers.lua#L165) with:

```lua
-- if lines_above > height then
if lines_above > height and lines_above < math.floor(vim.fn.winheight(0) / 2) then
  config.offset_y = -height - 3
end
```

and it seems ok. I'm using `nvim v0.8.3`.

Thank you 😊

**Comment by Issafalcon** [comment]
Good catch @goingtosleep ! I'll add this into my next update.

**Comment by Issafalcon** [comment]
Closing this as it has been fixed in the latest updates
