### ISSUE TITLE
Not getting active parameter highlight

### ISSUE THREAD

**Issue by tsakirist** [Issafalcon/lsp-overloads.nvim#37]
Hello, thanks for the plugin.

I just tried it and I can't seem to get active parameter highlight.
`LspSignatureActiveParameter` is set in my colorscheme but it doesn't seem to be applied.

Also, does the signature get automatically updated to highlight the next parameter, when a parameter is typed? Or do we have to use the keymaps for that? (Asking since I couldn't discern that since there is no highlighting)

Any ideas?

### Neovim

NVIM v0.10.0-dev-2737+g00b7428b3
Build type: Release
LuaJIT 2.1.1710088188

**Comment by fahadbr** [comment]
i'm also not getting the parameter highlight

NVIM v0.9.5                                                                                                                                                                                                                                   
Build type: Release                                                                                                                                                                                                                           
LuaJIT 2.1.1710088188

**Comment by fahadbr** [comment]
this workaround helped me. you can use your highlight group of choice of course. add this anytime after the colorscheme is loaded - 
```
      local labelhl = vim.api.nvim_get_hl_by_name('Function', true)
      vim.api.nvim_set_hl(0,
        "LspSignatureActiveParameter",
        { fg = labelhl.foreground, italic = true, bold = true })
```

**Comment by Issafalcon** [comment]
@tsakirist - A PR was recently raised and merged that makes it easier to set the highlight parameter for LspSignatureActiveParameter when using this plugin. 

That said, I'm not sure why it wasn't working for you before. You should be able to just set the highlight as @fahadbr mentioned, without any issue. I don't know how your colourscheme does it, but it could be setting it incorrectly, causing the highlighting to be "unset".

**Comment by altnp** [comment]
I am running into the same issue

![image](https://github.com/Issafalcon/lsp-overloads.nvim/assets/9112169/65a0ac26-4740-41a7-863b-339ad4e41b7e)

Confirmed the highlight is set:

![image](https://github.com/Issafalcon/lsp-overloads.nvim/assets/9112169/d93af264-0a5d-4f48-b457-40be7d5eefea)

**Comment by fneu** [comment]
I also got this issue.

The LspSignatureActiveParameter highlight group is set, but apparently not being used.
instead `:Inspect` shows `@markup.raw.block.markdown`.

This is on nvim 0.10.0 with the default colorscheme.

**Comment by Issafalcon** [comment]
#45 - This now fixes the issue that the above likely points to. The label of the signature help was being incorrectly identified for highlighting, despite correctly setting the highlight group.
