### ISSUE TITLE
`modify_signature` fails if `activeParameter` is nil

### ISSUE THREAD

**Issue by Natr1x** [Issafalcon/lsp-overloads.nvim#49]
The `modify_signature` which is used in the mappings for `sig_next`, `sig_prev`, `param_next`, and `param_prev` fails if neither of `SignatureHelp` or `SignatureInformation` has an `activeParameter` field.

This happens because `modify_signature` will always call `Signature:modify_active_param` which attempts to performs arithmetic operations on either `self.activeParameter` or `self.signatures[current_sig_index].activeParameter`.

**Comment by Issafalcon** [comment]
Fixed by PR
